require 'payment_services/qiwi'
require 'payment_services/adv_cash'
require 'payment_services/payeer'
require 'payment_services/perfect_money'
require 'payment_services/rbk'
require 'payment_services/yandex_money'
