# frozen_string_literal: true

# Copyright (c) 2018 FINFEX https://github.com/finfex

require 'payment_services/qiwi'
require 'payment_services/adv_cash'
require 'payment_services/payeer'
require 'payment_services/perfect_money'
require 'payment_services/rbk'
require 'payment_services/yandex_money'
require 'payment_services/yandex_money_payment_card'
require 'payment_services/e_voucher_usd'
require 'payment_services/e_voucher_eur'
require 'payment_services/wex_usd'
require 'payment_services/wex_rub'
require 'payment_services/exmo_usd'
require 'payment_services/exmo_rub'
require 'payment_services/exmo_eur'
require 'payment_services/ali_kassa'
require 'payment_services/ali_kassa_peer_to_peer'
require 'payment_services/any_money'
require 'payment_services/block_io'
require 'payment_services/crypto_apis'
require 'payment_services/appex_money'
require 'payment_services/kuna' 
require 'payment_services/liquid'
require 'payment_services/obmenka'
require 'payment_services/exmo'
require 'payment_services/binance'
require 'payment_services/master_processing'
require 'payment_services/crypto_apis_v2'
require 'payment_services/blockchair'
require 'payment_services/oko_otc'
require 'payment_services/paylama'
require 'payment_services/paylama_crypto'
require 'payment_services/ex_pay'
require 'payment_services/one_crypto'
require 'payment_services/any_pay'
require 'payment_services/coin_payments_hub'
require 'payment_services/pay_for_u'
require 'payment_services/best_api'
require 'payment_services/pay_for_u_h2h'
require 'payment_services/paylama_sbp'
